# Generated by Django 4.1.5 on 2024-01-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='thesis_docx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thesis', models.FileField(upload_to='thesis_files')),
            ],
        ),
    ]
