# Generated by Django 4.1.5 on 2024-01-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis_docx',
            name='author',
            field=models.CharField(default='author name', max_length=255),
            preserve_default=False,
        ),
    ]
