# Generated by Django 4.1.5 on 2024-01-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_thesis_docx_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis_docx',
            name='paragraphs',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
