# Generated by Django 4.1.5 on 2024-02-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_thesis_docx_paragraphs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis_docx',
            name='paragraphs',
            field=models.TextField(),
        ),
    ]
